# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: key-generator

dist: build/goreleaser

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
    -
     id: "cli-build"
     main: ./cmd/main.go
     binary: key-generator-cli
     ldflags:
       - -s -w -X github.com/katena-chain/key-generator/version.Version={{.Tag}} -X github.com/katena-chain/key-generator/version.GitCommit={{.Commit}}
     env:
      - CGO_ENABLED=0
     goos:
      - windows
      - linux
      - darwin
     goarch:
      - amd64

    - id: "gui-build_windows"
      main: ./gui/main.go
      binary: key-generator-gui
      env:
        - CGO_ENABLED=1
        - CC=x86_64-w64-mingw32-gcc
        - CCX=x86_64-w64-mingw32-g++
      goos:
        - windows
      goarch:
        - amd64

    - id: "gui-build_linux"
      main: ./gui/main.go
      binary: key-generator-gui
      env:
        - CGO_ENABLED=1
        - CC=gcc
        - CCX=gxx
      goos:
        - linux
      goarch:
        - amd64

    - id: "gui-build_darwin"
      main: ./gui/main.go
      binary: key-generator-gui
      env:
        - CGO_ENABLED=1
        - CC=o32-clang
      goos:
        - darwin
      goarch:
        - amd64

archives:
    -
     id: key-cli-generator_archive
     builds:
      - cli-build
     name_template: "cli_{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
     replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
     format: binary
    -
     id: key-gui-generator_archive
     builds:
      - gui-build_windows
      - gui-build_linux
      - gui-build_darwin
     name_template: "gui_{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
     replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
     format: binary

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
